// BG1 campaign
IF
  !Global("Campaign","LOCALS",1)
  GlobalLT("Chapter","GLOBAL",8)
THEN
  RESPONSE #100
    SetGlobal("Campaign","LOCALS",1)
    // DisplayString(Myself,~DEBUG: Campaign=1~)
    Continue()
END

// SoD campaign
IF
  !Global("Campaign","LOCALS",2)
  GlobalGT("Chapter","GLOBAL",7)
  GlobalLT("Chapter","GLOBAL",14)
THEN
  RESPONSE #100
    SetGlobal("Campaign","LOCALS",2)
    // DisplayString(Myself,~DEBUG: Campaign=2~)
    Continue()
END
