// Append to Cespenar's item upgrade script (botsmith.bcs)

IF
  Global("A7WOTP-FinalJudgmentUpgrade","AR4500",1)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("A7WOTP-FinalJudgmentUpgrade","AR4500",0)
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    SetGlobal("ItemMaker","GLOBAL",999) // required to trigger Cespenar's post-forge dialog
    GiveItemCreate("a7-ax09a",Player1,0,1,0)
    StartDialogueNoSet(Player1)
END
