// Basic thief combat script

IF
  Global("DefensePotion","LOCALS",0)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN24",Myself)  // Potion of Defense
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
    SetGlobal("DefensePotion","LOCALS",1)
    DisplayStringHead(Myself,@111)  // *quaffs a potion*
    UseItem("POTN24",Myself)  // Potion of Defense
END

IF
  HPPercentLT(Myself,50)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN55",Myself)  // Potion of Superior Healing
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
    DisplayStringHead(Myself,@111)  // *quaffs a potion*
    UseItem("POTN55",Myself)  // Potion of Superior Healing
END

IF
  HPPercentLT(Myself,50)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN52",Myself)  // Potion of Extra Healing
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
    DisplayStringHead(Myself,@111)  // *quaffs a potion*
    UseItem("POTN52",Myself)  // Potion of Extra Healing
END

IF
  HPPercentLT(Myself,50)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN08",Myself)  // Potion of Healing
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
    DisplayStringHead(Myself,@111)  // *quaffs a potion*
    UseItem("POTN08",Myself)  // Potion of Healing
END

IF
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  Global("HastePotion","LOCALS",0)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN14",Myself)  // Oil of Speed
THEN
  RESPONSE #100
    SetGlobal("HastePotion","LOCALS",1)
    SetGlobalTimer("SawEnemy","LOCALS",3)
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  Global("HastePotion","LOCALS",1)
  GlobalTimerExpired("SawEnemy","LOCALS")
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN14",Myself)  // Oil of Speed
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
    SetGlobal("HastePotion","LOCALS",2)
    DisplayStringHead(Myself,@111)  // *quaffs a potion*
    UseItem("POTN14",Myself)  // Oil of Speed
END

IF
  HitBy([ANYONE],CRUSHING)
  !HitBy([ANYONE],PIERCING)
  !HitBy([ANYONE],MISSILE)
  !HitBy([ANYONE],SLASHING)
  !HitBy([ANYONE],ACID)
  !HitBy([ANYONE],COLD)
  !HitBy([ANYONE],FIRE)
  !HitBy([ANYONE],POISON)
  Global("AbsorptionPotion","LOCALS",0)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN18",Myself)  // Potion of Absorption
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
    SetGlobal("AbsorptionPotion","LOCALS",1)
    DisplayStringHead(Myself,@111)  // *quaffs a potion*
    UseItem("POTN18",Myself)  // Potion of Absorption
END

IF
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN10",Myself)  // Potion of Invisibility
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
    DisplayStringHead(Myself,@111)  // *quaffs a potion*
    UseItem("POTN10",Myself)  // Potion of Invisibility
END

IF
  CheckStatGT(Myself,0,DETECTILLUSIONS)
  CheckStatLT(Myself,50,DETECTILLUSIONS)
  !GlobalTimerNotExpired("DetectIllusionTimer","LOCALS")
  Detect(NearestEnemyOf(Myself))
  OR(2)
    StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
    StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  Delay(2)
THEN
  RESPONSE #40
    SetGlobalTimer("DetectIllusionTimer","LOCALS",ONE_ROUND)
    DisplayStringHead(Myself,@113)  // Detects Illusion
    ReallyForceSpell(LastSeenBy(Myself),THIEF_DETECT_ILLUSION)
    Continue()
  RESPONSE #60
    SetGlobalTimer("DetectIllusionTimer","LOCALS",ONE_ROUND)
    DisplayStringHead(Myself,@114)  // Fails to detect illusions
    Continue()
END

IF
  !CheckStatLT(Myself,50,DETECTILLUSIONS)
  !GlobalTimerNotExpired("DetectIllusionTimer","LOCALS")
  Detect(NearestEnemyOf(Myself))
  OR(2)
    StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
    StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  Delay(2)
THEN
  RESPONSE #75
    SetGlobalTimer("DetectIllusionTimer","LOCALS",ONE_ROUND)
    DisplayStringHead(Myself,@113)  // Detects Illusion
    ReallyForceSpell(LastSeenBy(Myself),THIEF_DETECT_ILLUSION)
    Continue()
  RESPONSE #25
    SetGlobalTimer("DetectIllusionTimer","LOCALS",ONE_ROUND)
    DisplayStringHead(Myself,@114)  // Fails to detect illusions
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  !Range(LastSeenBy(Myself),7)
THEN
  RESPONSE #100
    EquipRanged()
    AttackReevaluate(LastSeenBy(Myself),45)
END

IF
  See(NearestEnemyOf(Myself))
  Range(LastSeenBy(Myself),7)
THEN
  RESPONSE #50
    RunAwayFromNoInterrupt(LastSeenBy(Myself),45)
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(LastSeenBy(Myself),45)
END

IF
  !See(NearestEnemyOf(Myself))
THEN
  RESPONSE #40
    RandomWalk()
  RESPONSE #40
    RandomTurn()
  RESPONSE #20
    NoAction()
END
