// Eyes of Mask: Challenge 3 Rogue 7 initialization

// initialization
IF
  Global("init","LOCALS",0)
  Switch("a7-ch3_start_index","MYAREA")
THEN
  RESPONSE #1
    SetGlobal("index","LOCALS",7)
    Continue()
  RESPONSE #2
    SetGlobal("index","LOCALS",6)
    Continue()
  RESPONSE #3
    SetGlobal("index","LOCALS",5)
    Continue()
  RESPONSE #4
    SetGlobal("index","LOCALS",4)
    Continue()
  RESPONSE #5
    SetGlobal("index","LOCALS",3)
    Continue()
  RESPONSE #6
    SetGlobal("index","LOCALS",2)
    Continue()
  RESPONSE #7
    SetGlobal("index","LOCALS",1)
    Continue()
  RESPONSE #8
    SetGlobal("index","LOCALS",9)
    Continue()
  RESPONSE #9
    SetGlobal("index","LOCALS",8)
    Continue()
END

IF
  Global("init","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("init","LOCALS",1)
    SetName(@624) // Edric
    Continue()
END
