// Nabassu combat script

IF
  See(NearestEnemyOf(Myself))
  OR(2)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),MAGE_ALL)
  Global("silence","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(LastSeenBy(Myself),TANARI_SILENCE)
    SetGlobal("silence","LOCALS",1)
END

IF
  See(SecondNearestEnemyOf(Myself))
  OR(2)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),MAGE_ALL)
  Global("silence","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(LastSeenBy(Myself),TANARI_SILENCE)
    SetGlobal("silence","LOCALS",1)
END

IF
  See(ThirdNearestEnemyOf(Myself))
  OR(2)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),MAGE_ALL)
  Global("silence","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(LastSeenBy(Myself),TANARI_SILENCE)
    SetGlobal("silence","LOCALS",1)
END

IF
  See(FourthNearestEnemyOf(Myself))
  OR(2)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),MAGE_ALL)
  Global("silence","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(LastSeenBy(Myself),TANARI_SILENCE)
    SetGlobal("silence","LOCALS",1)
END

IF
  See(FifthNearestEnemyOf(Myself))
  OR(2)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),MAGE_ALL)
  Global("silence","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(LastSeenBy(Myself),TANARI_SILENCE)
    SetGlobal("silence","LOCALS",1)
END

IF
  See(SixthNearestEnemyOf(Myself))
  OR(2)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),MAGE_ALL)
  Global("silence","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(LastSeenBy(Myself),TANARI_SILENCE)
    SetGlobal("silence","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  Global("abilities","LOCALS",0)
THEN
  RESPONSE #100
    ForceSpell(LastSeenBy(Myself),TANARI_DEATH_GAZE)
    SetGlobal("abilities","LOCALS",1)
    Wait(1)
    ForceSpell(LastSeenBy(Myself),TANARI_PARALYZE)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #60
    AttackOneRound(LastSeenBy(Myself))
    AttackOneRound(LastSeenBy(Myself))
  RESPONSE #20
    ForceSpell(LastSeenBy(Myself),TANARI_VAMPIRIC_TOUCH)
    AttackOneRound(LastSeenBy(Myself))
  RESPONSE #15
    ForceSpell(LastSeenBy(Myself),TANARI_PARALYZE)
    AttackOneRound(LastSeenBy(Myself))
  RESPONSE #5
    ForceSpell(LastSeenBy(Myself),TANARI_DEATH_GAZE)
    AttackOneRound(LastSeenBy(Myself))
END

IF
  See(NearestEnemyOf(Myself))
  CheckStatLT(LastSeenBy(Myself),1,DISABLE_CIRCLE)
THEN
  RESPONSE #70
    AttackReevaluate(LastSeenBy(Myself),30)
  RESPONSE #15
    ForceSpell(LastSeenBy(Myself),TANARI_VAMPIRIC_TOUCH)
    Wait(2)
  RESPONSE #10
    ForceSpell(LastSeenBy(Myself),TANARI_PARALYZE)
    Wait(2)
  RESPONSE #5
    ForceSpell(LastSeenBy(Myself),0)
    Wait(2)
END
