// Item: Planar Anchor

INCLUDE ~%MOD_FOLDER%/lib/functions.tph~

OUTER_SPRINT itm_resref ~a7-bl01~

ACTION_IF (has_bg2) BEGIN
  // Installing item
  COPY ~%MOD_FOLDER%/itm/%itm_resref%.itm~ ~override~
    LPF update_item_generic
      STR_VAR
        itm_resref
      RET
        icon_resref
        desc_image_resref
    END

  // Installing associated resources
  LAF install_item_resources_generic
  STR_VAR
    itm_resref
    icon_resref
    desc_image_resref
  END

  // Appending STATDESC table
  LAF get_tra_paths STR_VAR tra_res = EVAL ~%itm_resref%~ RET tra_language tra_fallback END
  WITH_TRA ~%tra_fallback%~ ~%tra_language%~ BEGIN
    LAF add_statdesc_entry
      INT_VAR strref = RESOLVE_STR_REF(@20) // Anchored
      STR_VAR resref = EVAL ~%itm_resref%d~
      RET statdesc_idx = index
    END
  END

  ACTION_IF (statdesc_idx < 0) BEGIN
    WARN ~WARNING: Could not add custom status portrait icon (%itm_resref%d)~
  END

  COPY ~%MOD_FOLDER%/bam/a7-bl01d.bam~ ~override~

  COPY_EXISTING ~%itm_resref%.itm~ ~override~
    LPF alter_item_effect_ex
      INT_VAR
        check_globals = 1
        match_opcode = 142  // Display portrait icon
        match_parameter2 = 94
        parameter2 = statdesc_idx
    END
  BUT_ONLY
END
