// Item: Fire Bolts of Piercing +1

INCLUDE ~%MOD_FOLDER%/lib/functions.tph~

OUTER_SPRINT itm_resref ~a7-bo11~

ACTION_IF (has_bg2) BEGIN
  // Installing projectiles
  ADD_PROJECTILE ~%MOD_FOLDER%/pro/a7-bopf1.pro~ ~Piercing_Bolt_Flame_Sub~
  ADD_PROJECTILE ~%MOD_FOLDER%/pro/a7-bopf.pro~ ~Piercing_Bolt_Flame~
  COPY_EXISTING ~a7-bopf.pro~ ~override~
    WRITE_SHORT 0x21a "a7-bopf1"
  BUT_ONLY

  COPY ~%MOD_FOLDER%/bam/a7-bopf.bam~ ~override~

  // Installing item
  COPY ~%MOD_FOLDER%/itm/%itm_resref%.itm~ ~override~
    LPF update_item_generic
      STR_VAR
        itm_resref
      RET
        icon_resref
        desc_image_resref
    END
    LPF ALTER_ITEM_HEADER INT_VAR projectile = "a7-bopf" END

  // Installing associated resources
  LAF install_item_resources_generic
  STR_VAR
    itm_resref
    icon_resref
    desc_image_resref
  END
END
