// Item: Cowl of Deepest Shadows

INCLUDE ~%MOD_FOLDER%/lib/functions.tph~

OUTER_SPRINT itm_resref ~a7-ck01~

ACTION_IF (has_bg2) BEGIN
  // Installing item
  COPY ~%MOD_FOLDER%/itm/%itm_resref%.itm~ ~override~
    LPF update_item_generic
      STR_VAR
        itm_resref
      RET
        icon_resref
        desc_image_resref
    END

  // Installing associated resources
  LAF install_item_resources_generic
  STR_VAR
    itm_resref
    icon_resref
    desc_image_resref
  END

  // Appending TOOLTIP table
  COPY_EXISTING ~spwi607.spl~ ~override~
    READ_LONG NAME1 mislead_strref
  BUT_ONLY
  OUTER_SPRINT tooltip_line ~%itm_resref% %mislead_strref% -1 -1~
  ACTION_TO_UPPER ~tooltip_line~
  APPEND ~tooltip.2da~ ~%tooltip_line%~

  // Appending SPLPROT table
  LAF get_splprot_entry
    INT_VAR
      stat = 0x106  // AREATYPE.IDS
      value = "-1"  // custom value
      relation = 7  // at least specified bits
    STR_VAR
      name = ~*_AREATYPEBITS>=n~
    RET
      splprot_idx = index
  END

  // Appending STATDESC table
  LAF get_tra_paths STR_VAR tra_res = EVAL ~%itm_resref%~ RET tra_language tra_fallback END
  WITH_TRA ~%tra_fallback%~ ~%tra_language%~ BEGIN
    LAF add_statdesc_entry
      INT_VAR strref = RESOLVE_STR_REF(@20) // Light Sensitive
      STR_VAR resref = ~A7-S509A~
      RET statdesc_idx1 = index
    END

    LAF add_statdesc_entry
      INT_VAR strref = RESOLVE_STR_REF(@21)  // Darkvision
      STR_VAR resref = ~A7-S509B~
      RET statdesc_idx2 = index
    END
  END

  ACTION_IF (statdesc_idx1 < 0 || statdesc_idx2 < 0) BEGIN
    WARN ~WARNING: Could not add custom status portrait icons (A7-S509A, A7-S509B)~
  END

  // Installing additional resources
  COPY ~%MOD_FOLDER%/spl/%itm_resref%a.spl~ ~override~
    LPF alter_item_effect_ex
      INT_VAR
        check_headers = 1
        match_opcode = 326  // Apply effects list
        parameter2 = splprot_idx
    END

  COPY ~%MOD_FOLDER%/spl/%itm_resref%c.spl~ ~override~
    LPF alter_item_effect_ex
      INT_VAR
        check_headers = 1
        match_opcode = 142  // Display portrait icon
        parameter2 = statdesc_idx1
    END

  COPY ~%MOD_FOLDER%/spl/%itm_resref%d.spl~ ~override~
    LPF alter_item_effect_ex
      INT_VAR
        check_headers = 1
        match_opcode = 142  // Display portrait icon
        parameter2 = statdesc_idx2
    END

  ACTION_FOR_EACH file IN ~%itm_resref%a.eff~
                          ~%itm_resref%b.spl~
                          ~a7-s509a.bam~
                          ~a7-s509b.bam~
  BEGIN
    ACTION_IF (NOT FILE_EXISTS_IN_GAME ~%file%~) BEGIN
      LAF EXT_OF_FILESPEC STR_VAR filespec = EVAL ~%file%~ RET ext END
      COPY ~%MOD_FOLDER%/%ext%/%file%~ ~override~
    END
  END
END
