// Item: Heart of the Fosterer

INCLUDE ~%MOD_FOLDER%/lib/functions.tph~
INCLUDE ~%MOD_FOLDER%/lib/find_free_anim_slot.tph~

OUTER_SPRINT itm_resref ~a7-mi17~
OUTER_SPRINT itm_resref_upper ~%itm_resref%~
ACTION_TO_UPPER ~itm_resref_upper~

// Installing item
COPY ~%MOD_FOLDER%/itm/%itm_resref%.itm~ ~override~
  LPF update_item_generic
    STR_VAR
      itm_resref
    RET
      icon_resref
      desc_image_resref
  END

// Installing associated resources
LAF install_item_resources_generic
STR_VAR
  itm_resref
  icon_resref
  desc_image_resref
END

COPY ~%MOD_FOLDER%/2da/a7-sohm.2da~ ~override~
     ~%MOD_FOLDER%/bam/a7-smok.bam~ ~override~
     ~%MOD_FOLDER%/eff/a7-sohfa.eff~ ~override~
     ~%MOD_FOLDER%/eff/a7-sohm.eff~ ~override~
     ~%MOD_FOLDER%/itm/a7-sohfa.itm~ ~override~
     ~%MOD_FOLDER%/itm/a7-sohim.itm~ ~override~
     ~%MOD_FOLDER%/itm/a7-sohsp.itm~ ~override~
     ~%MOD_FOLDER%/spl/a7-sohfa.spl~ ~override~
     ~%MOD_FOLDER%/vvc/a7-smok.vvc~ ~override~
     ~%MOD_FOLDER%/wav/a7-smok.wav~ ~override~

// Installing creature animation
OUTER_SPRINT ini_resref ~monster_icewind-sohmien~
OUTER_SPRINT ini_type   ~monster_icewind~
OUTER_SPRINT bam_resref ~a7so~
OUTER_SPRINT ids_label  ~A7_SOHMIEN~
LAF FIND_FREE_ANIM_SLOT STR_VAR type = EVAL ~%ini_type%~ RET anim_slot = slot END

ACTION_IF (anim_slot > 0) BEGIN
  OUTER_PATCH ~~ BEGIN
    SPRINTF slot_hex ~%x~ (anim_slot)
    INNER_PATCH_SAVE slot_hex ~%slot_hex%~ BEGIN DELETE_BYTES 0 2 END
    WHILE (STRING_LENGTH ~%slot_hex%~ < 4) BEGIN SPRINT slot_hex ~0%slot_hex%~ END
  END

  // installing INI file
  COPY ~%MOD_FOLDER%/ini/%ini_resref%.ini~ ~override/%slot_hex%.ini~

  // installing BAM files
  ACTION_BASH_FOR ~%MOD_FOLDER%/bam~ ~^%bam_resref%.*\.bam$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END

  // installing WAV files
  ACTION_BASH_FOR ~%MOD_FOLDER%/wav~ ~^a7-soh.*\.wav$~ BEGIN
    COPY ~%BASH_FOR_FILESPEC%~ ~override~
  END

  // adding ANIMATE.IDS entry
  APPEND ~animate.ids~ ~0x%slot_hex% %ids_label%~
  CLEAR_IDS_MAP
END ELSE BEGIN
  FAIL ~No free animation slot found for %ini_resref%.ini~
END

LAF get_tra_paths STR_VAR tra_res = EVAL ~%itm_resref%~ RET tra_language tra_fallback END
WITH_TRA ~%tra_fallback%~ ~%tra_language%~ BEGIN
  // installing creature
  COPY ~%MOD_FOLDER%/cre/a7-sohsu.cre~ ~override~
    SAY NAME1 @20 // Sohmien
    SAY NAME2 @20 // Sohmien
    WRITE_LONG 0x28 anim_slot

  COMPILE ~%MOD_FOLDER%/bcs/a7-sohm.baf~

  // adding ability tooltips
  OUTER_SET summon_strref = RESOLVE_STR_REF(@21) // Summon Sohmien
  APPEND ~tooltip.2da~ ~%itm_resref_upper%    %summon_strref%      -1         -1~
END
