// Item: Scroll of "Heart of Stone"

INCLUDE ~%MOD_FOLDER%/lib/functions.tph~

OUTER_SPRINT itm_resref ~a7-sp06~
OUTER_SPRINT itm_resref_upper ~%itm_resref%~
ACTION_TO_UPPER ~itm_resref_upper~

ACTION_IF (has_bg2) BEGIN
  LAF get_tra_paths STR_VAR tra_res = EVAL ~%itm_resref%~ RET tra_language tra_fallback END
  WITH_TRA ~%tra_fallback%~ ~%tra_language%~ BEGIN
    // installing portrait icon
    LAF add_statdesc_entry
      INT_VAR
        strref = RESOLVE_STR_REF(@20) // Heart of Stone
      STR_VAR
        resref = EVAL ~%itm_resref_upper%D~
      RET
        statdesc_idx = index
    END

    // installing spell
    LAF spell_slot_available INT_VAR type = 2 level = 8 RET slot END
    ACTION_IF (slot > 0) BEGIN
      ADD_SPELL ~%MOD_FOLDER%/spl/%itm_resref%.spl~ 2 8 ~WIZARD_HEART_OF_STONE~
      LAF RES_NAME_OF_SPELL_NUM INT_VAR spell_num = WIZARD_HEART_OF_STONE RET spl_resref = spell_res END
    END ELSE BEGIN
      COPY ~%MOD_FOLDER%/spl/%itm_resref%.spl~ ~override~
      OUTER_SPRINT spl_resref ~%itm_resref%~
    END

    COPY_EXISTING ~%spl_resref%.spl~ ~override~
      SAY NAME1 @1  // Heart of Stone
      SAY UNIDENTIFIED_DESC @11
      LPF ALTER_EFFECT
        INT_VAR match_opcode = 321  // Remove effects by resource
        STR_VAR resource = EVAL ~%spl_resref%~
      END
      LPF ALTER_EFFECT
        INT_VAR
          match_opcode = 142  // Display portrait icon
          parameter2 = statdesc_idx
      END
    BUT_ONLY

    // installing subspell
    COPY ~%MOD_FOLDER%/spl/%itm_resref%b.spl~ ~override~
      LPF ALTER_EFFECT
        INT_VAR
          match_opcode = 139  // Display string
          parameter1 = RESOLVE_STR_REF(@21) // Heart shattered
      END
      LPF ALTER_EFFECT
        INT_VAR match_opcode = 321  // Remove effects by resource
        STR_VAR resource = EVAL ~%spl_resref%~
      END

    // patching "Stone to Flesh"
    LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~WIZARD_STONE_TO_FLESH~ RET spell_num spell_res END
    COPY_EXISTING ~%spell_res%.spl~ ~override~
      LPF ADD_SPELL_EFFECT
        INT_VAR
          opcode = 321  // Remove effects by resource
          target = 2
          power = (spell_num MODULO 1000) / 100
          timing = 1
          dispel_resist = 2
        STR_VAR
          resource = EVAL ~%spl_resref%~
      END
    BUT_ONLY IF_EXISTS
  END

  COPY ~%MOD_FOLDER%/bam/%itm_resref%a.bam~ ~override~
       ~%MOD_FOLDER%/bam/%itm_resref%b.bam~ ~override~
       ~%MOD_FOLDER%/bam/%itm_resref%c.bam~ ~override~
       ~%MOD_FOLDER%/bam/%itm_resref%d.bam~ ~override~
       ~%MOD_FOLDER%/bmp/%itm_resref%a.bmp~ ~override~
       ~%MOD_FOLDER%/vvc/%itm_resref%a.vvc~ ~override~

  // Installing item
  COPY ~%MOD_FOLDER%/itm/%itm_resref%.itm~ ~override~
    LPF update_item_generic
      STR_VAR
        itm_resref
      RET
        icon_resref
        desc_image_resref
    END
    LPF ALTER_EFFECT
      INT_VAR match_opcode = 146  // Cast spell
      STR_VAR resource = EVAL ~%spl_resref%~
    END
    LPF ALTER_EFFECT
      INT_VAR match_opcode = 147  // Learn spell
      STR_VAR resource = EVAL ~%spl_resref%~
    END

  // Installing associated resources
  LAF install_item_resources_generic
  STR_VAR
    itm_resref
    icon_resref
    desc_image_resref
  END
END
